import type { Metadata } from 'next'
import './globals.css'
import { Providers } from '@/components/Providers'
import { FieldConfigProvider } from '@/context/FieldConfigContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <FieldConfigProvider>
          {children}
          </FieldConfigProvider>
        </Providers>
      </body>
    </html>
  )
}

